# Generated by Django 5.2.5 on 2025-09-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sold',
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='per_team_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
