# Generated by Django 5.2.5 on 2025-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_player_photo_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players_images/'),
        ),
    ]
